// Character data + 16x16 pixel portraits (one char = one pixel, see PAL).
const PAL = {
  k: '#2b1d14', s: '#eab38a', S: '#c98a62', e: '#1a1210', w: '#f4ead5',
  h: '#c0433a', H: '#8a2a26', b: '#6b4226', c: '#3d6aa8', C: '#284a7a',
  N: '#2f3f66', y: '#e8b33a', g: '#cfd8dc', m: '#9aa0a6', r: '#8a2a26',
  t: '#dcb65c', T: '#b08a3a', d: '#5a3a2a', o: '#6f7f3f', O: '#4f5f2a',
  q: '#2a9d8f', Q: '#1f7268', n: '#2b1d14', u: '#d9a07a', U: '#b8805c', p: '#b35d5d', v: '#e9c46a', V: '#c9a24a',
  G: '#4f6f2a', l: '#6f8f3a', L: '#c9d68a', a: '#e8b33a', x: '#c0433a',
  K: '#1a1210', j: '#3a2f44', B: '#e8b33a', z: '#f4ead5',
};

const Characters = {
  narrator: { name: '', blip: 0 },

  yunus: {
    name: 'يونس', blip: 260, face: 'face_yunus_big',
    portrait: [
      '................',
      '.....kkkkkk.....',
      '....khhhhhhk....',
      '...khhHhhHhhk...',
      '...kwwwwwwwwk...',
      '...kssssssssk...',
      '..kSsessssesSk..',
      '...kssssssssk...',
      '...ksbssssbsk...',
      '...kbbbSSbbbk...',
      '...kbbbbbbbbk...',
      '....kbbbbbbk....',
      '...kcckbbkcck...',
      '..kcccckkcccck..',
      '.kcccCccccCccck.',
      '.kCccccccccccCk.',
    ],
  },

  adel: {
    name: 'الريّس عادل', blip: 170, face: 'face_adel_big',
    portrait: [
      '................',
      '....kkkkkkkk....',
      '...kNNNNNNNNk...',
      '..kNNNNyyNNNNk..',
      '..kkkkkkkkkkkk..',
      '...kssssssssk...',
      '...kggksskggk...',
      '...kgeksskegk...',
      '...kssssSsssk...',
      '...kssmmmmssk...',
      '...ksssrrsssk...',
      '....kssssssk....',
      '...kNNkwwkNNk...',
      '..kNNNkwwkNNNk..',
      '.kNNyNNkwwkNNNk.',
      '.kNNNNNkwwkNNNk.',
    ],
  },

  marzouq: {
    name: 'العم مرزوق', blip: 130, face: 'face_marzouq_big',
    portrait: [
      '................',
      '....kkkkkkkk....',
      '...kttttttttk...',
      '.kkkTTTTTTTTkkk.',
      'kttttttttttttttk',
      '.kkkssssssssk...',
      '...ksessssesk...',
      '...kssssSsssk...',
      '...kwsssssswk...',
      '...kwwwwwwwwk...',
      '...kwwwddwwwk...',
      '...kwwwwwwwwk...',
      '....kwwwwwwk....',
      '...kookwwkook...',
      '..kooookwkooook.',
      '.kOooooooooooOk.',
    ],
  },

  voice: { name: 'صوت في الريح', blip: 90, eerie: true },

  sas: {
    name: 'ساس', blip: 330, face: 'face_sas_big',
    portrait: [
      '................',
      '....kkkkkkkk....',
      '...kqqqqqqqqk...',
      '..kqQqqqqqqQqk..',
      '..kkuuuuuuuukk..',
      '..kkuuuuuuuukk..',
      '..kkueuuuueukk..',
      '..knuuuuUuuunk..',
      '..knuuuuuuuunk..',
      '..knuuuppuuunk..',
      '..knnuuuuuunnk..',
      '..knnkuuuuknnk..',
      '..knkvvwwvvknk..',
      '..knvvvwwvvvkk..',
      '..knvVvwwvVvvk..',
      '.kvvVvvwwvvVvvk.',
    ],
  },

  hams: {
    name: 'همس', blip: 150, face: 'an_hams',
    portrait: [
      '................',
      '.....kkkkkk.....',
      '....kllllllk....',
      '...kllGllGllk...',
      '...klakllkalk...',
      '...kllllllllk...',
      '....kLLLLLLk....',
      '.....kLxxLk.....',
      '......x..x......',
      '.....kllllk.....',
      '....kllGGllk....',
      '...kllGllGllk...',
      '..kllGlllllGlk..',
      '..klLLLLLLLLlk..',
      '.kllllGllllGllk.',
      '.kkkkkkkkkkkkkk.',
    ],
  },

  fahma: {
    name: 'فحمة', blip: 520, face: 'an_crow',
    portrait: [
      '................',
      '......KKKK......',
      '....KKjjjjKK....',
      '...KjjKKKKjjK...',
      '...KKzKKKKKKK...',
      '...KKKKKKKBBBB..',
      '...KKKKKKKBBB...',
      '...KjjKKKKK.....',
      '..KjjjjKKKKK....',
      '..KjKKjjKKKK....',
      '.KjjKKKzKKKKK...',
      '.KKjjKKKKKKKK...',
      '..KKKKKKKKKK....',
      '....KKKKKKK.....',
      '.....y...y......',
      '....yyy.yyy.....',
    ],
  },

  island: { name: 'الجزيرة', blip: 60, eerie: true },
  manager: { name: 'المدير عادل', blip: 170, portrait: 'adel' },
  janitor: { name: 'العم مرزوق', blip: 130, portrait: 'marzouq' },
};
