// Explorable maps. Rows are tiles (see tiles.js); letters/digits in `legend` are objects placed on `floor`.
// Object types: pickup, fish, fire, look, exit, zone. `label` may contain '#' → replaced by the object's index.
const Maps = (() => {
  const spawn = { Y: { type: 'spawn' }, S: { type: 'spawn' } };

  return {
    beach: {
      name: 'شاطئ الجزيرة', floor: '.', fill: '~', music: 'island', amb: ['ocean', 'breath', 'gulls'],
      rows: [
        'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
        'vTTTTTTTTTTTT;N;TTTTTTTTTTTTTTTv',
        'vTT;;,,;TTT,,;,,,TTT;,,;;TTTTTTv',
        'vT;1,,,,,,,,,,,,,,,,,,,,,,,1;;Tv',
        'P,,,,,,P,,,,,,,,,,,,,,,P,,,,,,,P',
        ',,,,,,,,,,,,,,,,,,,,C,,,,,,,,,,,',
        '................................',
        '......1.........................',
        '..P.......................P.....',
        '...............F........1.......',
        '.......3........................',
        '..................r.............',
        '..........1...........r.......1.',
        '......................4.........',
        '............Y....K..............',
        '-----......S.............-------',
        '~----------...B..---------------',
        '~~~~----2---------2------2----~~',
        '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
        '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~',
      ],
      legend: {
        ...spawn,
        '1': { type: 'pickup', art: 'wood', quest: 'wood', name: 'حطب', verb: 'اجمع الحطب' },
        '2': { type: 'fish', art: 'fishspot', verb: 'اصطد السمك', floor: '-', only: 'yunus' },
        'K': { type: 'look', art: 'charts', label: 'b_charts', verb: 'اقرأ خرائط أبي ساس', only: 'sas', once: true },
        'F': { type: 'fire', art: 'fire' },
        '3': { type: 'look', art: 'note', label: 'b_shell', verb: 'افحص الصدفة المنقوشة', once: true },
        '4': { type: 'look', art: 'eye', label: 'b_eye', verb: 'انظر في البركة' },
        'B': { type: 'look', art: 'boat', label: 'b_boat', verb: 'تفقّد القارب', solid: true },
        'C': { type: 'look', art: 'crow', label: 'b_crow', verb: 'اقترب من الغراب', floor: ',', show: f => f.nightDone && !f.crowFollowed },
        'N': { type: 'exit', art: 'exit', to: 'jungle', at: 'M', verb: 'ادخل الغابة', floor: ';', cond: s => s.flags.nightDone && !s.flags.finalBeach, locked: 'ليس الآن...' },
      },
    },

    jungle: {
      name: 'الغابة التي تتنفّس', floor: ';', fill: 'v', music: 'island', amb: ['jungle', 'breath'], flesh: true, breathUI: true,
      onEnter: 'j_enter',
      rows: [
        'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
        'vTTTTTTTTTTTTTfKfTTTTTTTTTTTTTTv',
        'vTT;;;;TTTTffffffTTTT;;5;TTTTTTv',
        'vT;;6;;;TTTfCffffTTT;;;;;;TTTTTv',
        'vT;;;;;;TTTRRRRRRTTT;;TTTTTTTTTv',
        'vTF;TT;;;;;;;;;;;;;;;;;;;;;TTTTv',
        'vTT;TT;;E;;;TTTT;;;;;;E;;;;;TTTv',
        'vTT;;;;;;;;;TTTT;;TTTTTT;;;;;TTv',
        'vT;;TTTTT;;;;;;;;;TTTTTT;;H;;TTv',
        'vT;;TTTTT;;;J;;;;;;;F;;;;;;;;TTv',
        'vT;;;;;;;;;;;;TTTTTTTT;;;;;;;TTv',
        'vTTT5;;;;;;;;;TTTTTTTT;;;6;;;TTv',
        'vTTTTTTTT;;;;;;;;;;;;;;;;;;;TTTv',
        'vTT;;;;TT;;X;;;;;TTTTT;;;;;;TTTv',
        'vTT;6;;TT;;;;;;;;TTTTT;;;5;;TTTv',
        'vTT;;;;;;;;TTTTT;;;;F;;;;;;TTTTv',
        'vTTTTTT;;;;TTTTT;;TTTTTTTTTTTTTv',
        'vTTTTTT;;;;;;;;;;;TTTTTTTTTTTTTv',
        'vTTTTTTTTTTTT;;;TTTTTTTTTTTTTTTv',
        'vTTTTTTTTTTTT;Y;TTTTTTTTTTTTTTTv',
        'vTTTTTTTTTTTTS;;TTTTTTTTTTTTTTTv',
        'vTTTTTTTTTTTT;M;TTTTTTTTTTTTTTTv',
        'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
      ],
      legend: {
        ...spawn,
        '5': { type: 'look', art: 'note', label: 'j_note#', verb: 'اقرأ الورقة', once: true },
        '6': { type: 'pickup', art: 'fruit', name: 'ثمار غريبة', stat: { supplies: 1 }, verb: 'اقطف الثمار' },
        'F': { type: 'pickup', art: 'fiber', quest: 'fiber', name: 'ألياف', verb: 'اجمع الألياف', only: 'sas' },
        'E': { type: 'look', art: 'eyeflower', label: 'j_flower#', verb: 'تأمّل الزهرة', once: true },
        'J': { type: 'look', art: 'frogs', label: 'j_frogs', verb: 'اقترب من الضفادع', once: true },
        'X': { type: 'zone', art: 'boar', label: 'j_boar', once: true, show: f => !f.boarGone },
        'H': { type: 'look', art: 'spring', label: 'j_spring', verb: 'اشرب من النبع', once: true },
        'C': { type: 'look', art: 'crow_trapped', label: 'j_crow', verb: 'حرّر الغراب', floor: 'f', once: true },
        'K': { type: 'exit', art: 'exit', label: 'a3_start', verb: 'ادخل الكهف', floor: 'f', cond: s => s.flags.crowFreed, locked: 'لن نترك الغراب عالقًا.' },
        'M': { type: 'exit', art: 'exit', to: 'beach', at: 'N', verb: 'عُد إلى الشاطئ' },
      },
    },

    cave: {
      name: 'الحنجرة', floor: 'o', fill: '#', music: 'cave', amb: ['drip', 'breath'], dark: 0.93, breathUI: true,
      rows: [
        '##############################',
        '#############oUo##############',
        '#############oYo##############',
        '############ooSoo#############',
        '###########ooooooo############',
        '####oooo###IIIIIII####ooooo###',
        '####o5oo###oooHooo####oo6oo###',
        '####oooooooooooooooooooooo####',
        '#########ooooooooooo##########',
        '#########tttttttttttt#########',
        '#########VVVVVVVVVVVV#########',
        '###ooooooooooooooooooooooo####',
        '###oaaaaaaaaaaaaaaaaaaaaao####',
        '###oaaaaaaaaaaaaaaaaaaaaao####',
        '###oaaaaaaaaaaaaaaaaaaaaao####',
        '###AAAAAAAAAAAAAAAAAAAAAAA####',
        '##########ooooo7ooo###########',
        '############ooZoo#############',
        '##############################',
      ],
      legend: {
        ...spawn,
        'U': { type: 'exit', art: 'exit', to: 'jungle', at: 'K', verb: 'اخرج إلى الغابة' },
        'I': { type: 'zone', label: 'c_hams', once: true, floor: 'o', show: f => !f.metHams },
        'H': { type: 'look', art: 'hams', label: 'c_hams', verb: 'اقترب من الصوت', glow: 30, show: f => !f.metHams },
        '5': { type: 'look', art: 'note', label: 'c_note1', verb: 'اقرأ النقش', once: true },
        '7': { type: 'look', art: 'note', label: 'c_note2', verb: 'اقرأ النقش', once: true, only: 'sas' },
        '6': { type: 'pickup', art: 'oil', name: 'زيت الفانوس', set: { lanternOil: true }, quest: 'oil', verb: 'التقط القارورة', only: 'yunus' },
        'V': { type: 'zone', quest: 'teeth', once: true, floor: 'o' },
        'A': { type: 'zone', quest: 'acid', once: true, floor: 'o' },
        'Z': { type: 'exit', art: 'exit', label: 'a3_ribs', verb: 'انزل إلى الأعماق', cond: s => s.flags.metHams, locked: 'الظلام هنا أعمق من أن تنزل وحدك.' },
      },
    },

    ribs: {
      name: 'مقبرة السفن', floor: 'f', fill: 'b', music: 'heart', amb: ['heartbeat', 'breath', 'drip'], dark: 0.6, flesh: true, breathUI: true,
      rows: [
        'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
        'bfffffffbbbbbbbbbbbbbbbbbb#U#bbb',
        'bff8fffffb==========bbbbbb###bbb',
        'bfffffffff===L======fffffffffffb',
        'bfffbbbbff==========ffffCffffffb',
        'bfffbffffffffffffffffffffffffffb',
        'bYSfbfffbbbbbbbbbffffbbbbbbffffb',
        'bfffbfffbttt8tttbffffbaaaabffffb',
        'bfffffffbtttttttbffffba9aabff8fb',
        'bffffffffffffffQfffffffffffffffb',
        'bbbbbbbbbbbbbbkbbbbbbbbbbbbbbbbb',
        'bbbbbbbbbbbbbRRRbbbbbbbbbbbbbbbb',
        'bbbbbbbbbbbffffffbbbbbbbbbbbbbbb',
        'bbbbbbbbbffffffffffbbbbbbbbbbbbb',
        'bbbbbbbbbffffXffffffbbbbbbbbbbbb',
        'bbbbbbbbbffffffffffbbbbbbbbbbbbb',
        'bbbbbbbbbbbfffEfffbbbbbbbbbbbbbb',
        'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
      ],
      legend: {
        ...spawn,
        '8': { type: 'pickup', art: 'plank', quest: 'planks', name: 'لوح سليم', verb: 'التقط اللوح', only: 'yunus' },
        'L': { type: 'pickup', art: 'sail', quest: 'sail', name: 'قماش قلع', verb: 'خذ القماش', floor: '=', only: 'sas' },
        'U': { type: 'deco', art: 'rudder', floor: '#', show: f => !f.rudderGot },
        'C': { type: 'look', art: 'crow', label: 'r_crow', verb: 'نادِ فحمة', show: f => !f.rudderGot },
        'Q': { type: 'look', art: 'crack', label: 'r_crack', verb: 'افحص الشق', show: f => !f.hamsOpened },
        '9': { type: 'look', art: 'note', label: 'r_note', verb: 'اقرأ السجلّ', floor: 'a', once: true },
        'X': { type: 'zone', art: 'glow', label: 'r_heart', once: true },
        'E': { type: 'exit', art: 'exit', label: 'a3_escape', verb: 'اهرب نحو الضوء', cond: s => s.flags.heartDone, locked: 'القلب ما زال يسدّ الطريق.' },
      },
    },

    office: {
      name: 'الطابق الرابع', floor: '_', fill: 'W', music: 'office', amb: ['hum', 'clock', 'keys'], style: 'office', follow: false, sasLabel: 'o_sas',
      rows: [
        'WWWGGGWWWWWWWGGGWWWW',
        'W__C_______________W',
        'W_DD1__DDL__DD__5__W',
        'W__Y____S_____6____W',
        'W__________________W',
        'W_DD___DD___DD___4_W',
        'W__________________W',
        'WccccccccccccccccccW',
        'Wcc3ccccccccJccccccW',
        'WWWWWWWWcccWWWWMWWWW',
        'WWWWWWWWcEcWWWWWWWWW',
        'WWWWWWWWWWWWWWWWWWWW',
      ],
      legend: {
        ...spawn,
        'C': { type: 'look', art: 'window_crow', label: 'o_crow', verb: 'انظر من النافذة' },
        '1': { type: 'look', art: 'computer', label: 'o_report', verb: 'اكتب التقرير', only: 'yunus' },
        'L': { type: 'look', art: 'computer', label: 'o_ledger', verb: 'افتحي جدول المحاسبة', only: 'sas', show: () => Net.connected },
        '5': { type: 'look', art: 'aquarium', label: 'o_aquarium', verb: 'تأمّل الحوض' },
        '6': { type: 'look', art: 'cable', label: 'o_cable', verb: 'افحص السلك' },
        '4': { type: 'look', art: 'coffee', label: 'o_coffee', verb: 'اصنع قهوة' },
        '3': { type: 'look', art: 'printer', label: 'o_print', verb: 'اطبع التقرير', floor: 'c' },
        'J': { type: 'look', art: 'janitor', label: 'o_janitor', verb: 'تحدّث مع عامل النظافة', floor: 'c' },
        'M': { type: 'look', art: 'door', label: 'o_manager', verb: 'ادخل مكتب المدير', floor: 'W' },
        'E': { type: 'look', art: 'exitdoor', label: 'o_exit', verb: 'باب الخروج', floor: 'c' },
      },
    },
  };
})();
